server:
  port: 12000
  servlet:
    context-path: /
logging:
  level:
    .: info
    cn.lhfei.monitor: debug
    cn.lhfei.monitor.orm.mapper: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# Druid datasource settings:
spring:
  datasource:
    url: jdbc:mysql://10.170.131.75:3306/monitor_admin?useSSL=false
    username: monitor
    password: NxMonitor_1473
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  kafka:
    consumer:
      group-id: test
      auto-offset-reset: latest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    #bootstrap-servers: 192.168.134.92:9092
    bootstrap-servers: 11.91.142.3:9092,11.91.142.4:9092,11.91.142.5:9092
swagger:
  enabled: true
  
mybatis:
  type-aliases-package: cn.lhfei.monitor.orm.domain
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:/mybatis/mappers/OpsLogMapper.xml
  - classpath:/mybatis/mappers/ModuleMapper.xml
  
